name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # Укажите вашу версию Go

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test


  build:
    name: Build Binary
    needs: test  # Зависит от успешного прохождения тестов
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: log-analyzer
          path: bin/log-analyzer